version: '3.8'

services:
  flask-app2:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
